version: '3.8'
services:
  blog-service:
    build: .
    ports:
      - "3004:3004"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - kong-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9092:9092"
    networks:
      - kong-net

  grafana:
    image: grafana/grafana
    ports:
      - "3005:3000"
    networks:
      - kong-net

  postgres-blog:
    image: postgres
    restart: always
    ports: 
      - "5433:5432"
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog
    networks:
      - kong-net

networks:
  kong-net:
    external: true