version: '3.8'
services:
  main-service:
    build: .
    ports:
      - "3010:3010"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - kong-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9095:9095"
    networks:
      - kong-net

  grafana:
    image: grafana/grafana
    ports:
      - "3011:3011"
    networks:
      - kong-net

networks:
  kong-net:
    external: true
