version: '3.8'
services:
  recommendation-service:
    build: .
    ports:
      - "3012:3012"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - kong-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9096:9096"
    networks:
      - kong-net

  grafana:
    image: grafana/grafana
    ports:
      - "3013:3013"
    networks:
      - kong-net

networks:
  kong-net:
    external: true
