version: '3.8'
services:
  business-service:
    build: .
    ports:
      - "3006:3006"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - kong-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9093:9093"
    networks:
      - kong-net

  grafana:
    image: grafana/grafana
    ports:
      - "3007:3000"
    networks:
      - kong-net

networks:
  kong-net:
    external: true
