version: '3.8'
services:
  reports-service:
    build: .
    ports:
      - "3014:3014"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - kong-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9097:9097"
    networks:
      - kong-net

  grafana:
    image: grafana/grafana
    ports:
      - "3015:3015"
    networks:
      - kong-net

  mongodb:
      image: mongodb/mongodb-community-server:6.0-ubi8
      ports:
        - '27028:27017'
      volumes:
        - mongodb_data:/data/db
      networks:
        - kong-net

networks:
  kong-net:
    external: true
  
volumes:
  mongodb_data:
